<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Install Definition Rule file describing relations between board files and devices.

Devices must be specified by the part name without package and speed grade,
for instance xc7z010 or xc7a100t
-->
<idr>
	<device_rule device="xc7a200t" part="xc7a200tfbg676-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/ac701"></dir>
	</device_rule>
	<device_rule device="xck24" part="xck24-ubva530-2LV-c">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/k24c"></dir>
	</device_rule>
	<device_rule device="xck24" part="xck24-ubva530-2lvi-i">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/k24i"></dir>
	</device_rule>
	<device_rule device="xck26" part="xck26-sfvc784-2LV-c">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/k26c"></dir>
	</device_rule>
	<device_rule device="xck26" part="xck26-sfvc784-2LVI-i">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/k26i"></dir>
	</device_rule>
	<device_rule device="xc7k325t" part="xc7k325tffg900-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kc705"></dir>
	</device_rule>
	<device_rule device="xcku040" part="xcku040-ffva1156-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kcu105"></dir>
	</device_rule>
	<device_rule device="xcku5p" part="xcku5p-ffvb676-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kcu116"></dir>
	</device_rule>
	<device_rule device="xcku115" part="xcku115-flvb2104-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kcu1500"></dir>
	</device_rule>
	<device_rule device="xck24" part="xck24-ubva530-2LV-c">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kd240_som"></dir>
	</device_rule>
	<device_rule device="xck26" part="xck26-sfvc784-2LV-c">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kr260_som"></dir>
	</device_rule>
	<device_rule device="xck26" part="xck26-sfvc784-2LV-c">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kv260_som"></dir>
	</device_rule>
	<device_rule device="xc7s100" part="xc7s100fgga676-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/sp701"></dir>
	</device_rule>
	<device_rule device="xcvc1902" part="xcvc1902-vsva2197-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/tenzing"></dir>
	</device_rule>
	<device_rule device="xc7vx485t" part="xc7vx485tffg1761-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vc707"></dir>
	</device_rule>
	<device_rule device="xc7vx690t" part="xc7vx690tffg1761-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vc709"></dir>
	</device_rule>
	<device_rule device="xcvc1902" part="xcvc1902-vsva2197-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190"></dir>
	</device_rule>
	<device_rule device="xcvc1902" part="xcvc1902-vsva2197-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190_newl/production"></dir>
	</device_rule>
	<device_rule device="xcvu095" part="xcvu095-ffva2104-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vcu108"></dir>
	</device_rule>
	<device_rule device="xcvu190" part="xcvu190-flgc2104-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vcu110"></dir>
	</device_rule>
	<device_rule device="xcvu9p" part="xcvu9p-flga2104-2L-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vcu118"></dir>
	</device_rule>
	<device_rule device="xcvu37p" part="xcvu37p-fsvh2892-2L-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vcu128"></dir>
	</device_rule>
	<device_rule device="xcvu29p" part="xcvu29p-fsga2577-2L-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vcu129"></dir>
	</device_rule>
	<device_rule device="xcvu9p" part="xcvu9p-fsgd2104-2L-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vcu1525"></dir>
	</device_rule>
	<device_rule device="xcve2802" part="xcve2802-vsvh1760-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vek280/production"></dir>
	</device_rule>
	<device_rule device="xczu19eg" part="xczu19eg-ffvd1760-2L-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vermeo_t1_mpsoc"></dir>
	</device_rule>
	<device_rule device="xczu21dr" part="xczu21dr-ffvd1156-2L-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vermeo_t1_rfsoc"></dir>
	</device_rule>
	<device_rule device="xcvh1582" part="xcvh1582-vsva3697-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vhk158/production"></dir>
	</device_rule>
	<device_rule device="xcvm1802" part="xcvm1802-vsva2197-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vmk180/production"></dir>
	</device_rule>
	<device_rule device="xcvm1802" part="xcvm1802-vsva2197-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vmk180_newl/production"></dir>
	</device_rule>
	<device_rule device="xcvp1202" part="xcvp1202-vsva2785-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vpk120/production"></dir>
	</device_rule>
	<device_rule device="xcvp1802" part="xcvp1802-lsvc4072-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vpk180/production"></dir>
	</device_rule>
	<device_rule device="xc7z020" part="xc7z020clg484-1">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zc702"></dir>
	</device_rule>
	<device_rule device="xc7z045" part="xc7z045ffg900-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zc706"></dir>
	</device_rule>
	<device_rule device="xczu9eg" part="xczu9eg-ffvb1156-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu102"></dir>
	</device_rule>
	<device_rule device="xczu7ev" part="xczu7ev-ffvc1156-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu104"></dir>
	</device_rule>
	<device_rule device="xczu7ev" part="xczu7ev-ffvc1156-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu106"></dir>
	</device_rule>
	<device_rule device="xczu28dr" part="xczu28dr-ffvg1517-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu111"></dir>
	</device_rule>
	<device_rule device="xczu29dr" part="xczu29dr-ffvf1760-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu1275"></dir>
	</device_rule>
	<device_rule device="xczu39dr" part="xczu39dr-ffvf1760-2-i">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu1285"></dir>
	</device_rule>
	<device_rule device="xczu48dr" part="xczu48dr-fsvg1517-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu208/production"></dir>
	</device_rule>
	<device_rule device="xczu49dr" part="xczu49dr-ffvf1760-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu216/production"></dir>
	</device_rule>
	<device_rule device="xczu58dr" part="xczu58dr-fsvg1517-2-i">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu208ld/production"></dir>
	</device_rule>
	<device_rule device="xczu59dr" part="xczu59dr-ffvf1760-2-i">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu216ld/production"></dir>
	</device_rule>
	<device_rule device="xczu67dr" part="xczu67dr-fsve1156-2-i">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu670"></dir>
	</device_rule>
	<device_rule device="xczu57dr" part="xczu57dr-fsve1156-2-i">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu670ld"></dir>
	</device_rule>
	<device_rule device="xck24" part="xck24-ubva530-2lv-c">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kd240_carrier"></dir>
	</device_rule>
	<device_rule device="xck26" part="xck26-sfvc784-2LV">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kr260_carrier"></dir>
	</device_rule>
	<device_rule device="xck26" part="xck26-sfvc784-2LV">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/kv260_carrier"></dir>
	</device_rule>
	<device_rule device="xcve2802" part="xcve2802-vsvh1760-2MP">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/li-imx274-mipi-versal"></dir>
	</device_rule>
	<device_rule device="xczu7ev" part="xczu7ev-ffvc1156-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/xm105"></dir>
	</device_rule>
	<device_rule device="xczu9eg" part="xczu9eg-ffvb1156-2">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/li-imx274-mipi"></dir>
	</device_rule>
	<device_rule device="xcve2302" part="xcve2302-sfva784-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/emb-plus-vpr-4616"></dir>
	</device_rule>
	<device_rule device="xcv80" part="xcv80-lsva4737-2MHP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/v80"></dir>
	</device_rule>
	<device_rule device="xcsu35p" part="xcsu35p-sbvb625-2-e">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/scu35"></dir>
	</device_rule>
	<device_rule device="xc2ve3858" part="xc2ve3858-ssva2112-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vek385"></dir>
	</device_rule>
	<device_rule device="xc2ve3858" part="xc2ve3858-ssva2112-2MP-e-S">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vek385_2"></dir>
	</device_rule>
	<device_rule device="xcvr1602" part="xcvr1602-vsva2488-2MP-e-S-es1">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/vrk160"></dir>
	</device_rule>
	<device_rule device="xcsu200p" part="xcsu200p-sbva1024-2-e-es1">
	<dir src="data/xhub/boards/XilinxBoardStore/boards/Xilinx/scu200/es"></dir>
	</device_rule>
</idr>
